name: Build Docker Images

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'

jobs:
  build-api:
    name: Build API Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            trieve/firecrawl
          tags: |
            type=raw,latest
            type=sha

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/api
          file: ./apps/api/Dockerfile
          push: true
          tags: trieve/firecrawl:pr-${{ github.event.number }}
          build-args: |
            PORT=8080

  build-puppeteer:
    name: Build Puppeteer Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            trieve/puppeteer-service-ts
          tags: |
            type=raw,latest
            type=sha

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/puppeteer-service-ts/
          file: ./apps/puppeteer-service-ts/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            PORT=3000
